/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 * @author Andrey Salamanca, Maverick Madrigal, Estefani Valverde
 * @version (25/11/2022)
 */
public class Extras extends javax.swing.JFrame {

    /**
     * Creates new form Extras
     */
    public Extras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        wifi = new javax.swing.JCheckBox();
        asist = new javax.swing.JCheckBox();
        gps = new javax.swing.JCheckBox();
        ninio = new javax.swing.JCheckBox();
        danio = new javax.swing.JCheckBox();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Servicios extra");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Puede escoger varios");

        wifi.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        wifi.setText("Wifi ilimitado ($15 /dia)");
        wifi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                wifiStateChanged(evt);
            }
        });

        asist.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        asist.setText("Asistencia en carretera ($3,99 /dia)");
        asist.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                asistStateChanged(evt);
            }
        });
        asist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asistActionPerformed(evt);
            }
        });

        gps.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        gps.setText("GPS ($13,99 /dia)");
        gps.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gpsStateChanged(evt);
            }
        });

        ninio.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        ninio.setText("Asiento p/niño ($6,99 /dia)");
        ninio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ninioStateChanged(evt);
            }
        });

        danio.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        danio.setText("Cobertura por daños a terceros ($12,99 /dia)");
        danio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                danioStateChanged(evt);
            }
        });

        aceptar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wifi)
                    .addComponent(gps)
                    .addComponent(ninio)
                    .addComponent(danio)
                    .addComponent(asist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)))
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(wifi)
                .addGap(18, 18, 18)
                .addComponent(asist)
                .addGap(18, 18, 18)
                .addComponent(gps)
                .addGap(10, 10, 10)
                .addComponent(ninio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(danio)
                    .addComponent(aceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asistActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarActionPerformed

    private void wifiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_wifiStateChanged
                
    }//GEN-LAST:event_wifiStateChanged

    private void asistStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_asistStateChanged
        
    }//GEN-LAST:event_asistStateChanged

    private void gpsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gpsStateChanged
       
    }//GEN-LAST:event_gpsStateChanged

    private void ninioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ninioStateChanged
        
    }//GEN-LAST:event_ninioStateChanged

    private void danioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_danioStateChanged
        
    }//GEN-LAST:event_danioStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Extras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Extras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton aceptar;
    public javax.swing.JCheckBox asist;
    public javax.swing.JButton cancelar;
    public javax.swing.JCheckBox danio;
    public javax.swing.JCheckBox gps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JCheckBox ninio;
    public javax.swing.JCheckBox wifi;
    // End of variables declaration//GEN-END:variables
}
